WisdomTrade/WisdomTradeApp/Controllers/AlgorithmicTradingController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Linq;
using System.Threading.Tasks;
using WisdomTradeApp.APIClients.AlphaVantageService;
using WisdomTradeApp.Controllers.Helpers;

namespace WisdomTradeApp.Controllers
{
    public class AlgorithmicTradingController : Controller
    {
        private TimeSeriesService timeSeriesService;
        private AlgorithmicTradingControllerHelper atcHelper;

        public AlgorithmicTradingController()
        {
            timeSeriesService = new TimeSeriesService();
            atcHelper = new AlgorithmicTradingControllerHelper();
        }

        // GET: AlgorithmicTradingViewModels
        public async Task<IActionResult> Index()
        {
            // get data
            await timeSeriesService.MakeRequestAsync("IBM");
            var closingPrice = timeSeriesService.Responses.Select(r => r.Close);
            var dates = timeSeriesService.Responses.Select(r => r.Date);

            // calculate sma
            var sma1 = atcHelper.GetSMA(closingPrice.ToArray(), dates.ToArray(), 5);
            var sma2 = atcHelper.GetSMA(closingPrice.ToArray(), dates.ToArray(), 10);

            // data to pass
            ViewBag.Dates = JsonConvert.SerializeObject(dates);
            ViewBag.ClosingPrice = JsonConvert.SerializeObject(closingPrice);
            ViewBag.SMAClosingPrice1 = JsonConvert.SerializeObject(sma1.ClosingPrice);
            ViewBag.SMAClosingPrice2 = JsonConvert.SerializeObject(sma2.ClosingPrice);

            // IN-DEV: find entry points and exit point
            var keyPoints = atcHelper.GetEntryPoint(closingPrice.ToList<decimal>(), sma1.ClosingPrice, dates.ToList<string>());
            ViewBag.EntryPoint = keyPoints.EntryPoint;
            ViewBag.EntryPointDate = keyPoints.Date;

            return View();
        }
    }
}

WisdomTrade/WisdomTradeApp/Controllers/PositionsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WisdomTradeApp.Data;
using WisdomTradeApp.Data.Services;
using WisdomTradeApp.Models;

namespace WisdomTradeApp.Controllers
{
    [Authorize]
    public class PositionsController : Controller
    {
        private IPositionService _positionService;

        public PositionsController(ApplicationDbContext context, IPositionService positionService)
        {
            _positionService = positionService;
        }

        // GET: Positions
        public async Task<IActionResult> Index()
        {
            return View(await _positionService.GetAllPositionsAsync());
        }

        // GET: Positions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var position = await _positionService.GetPositionAsync((int)id);

            if (position == null) return NotFound();

            return View(position);
        }

        // GET: Positions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Positions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ticker,Date,PricePrediction")] Position position)
        {
            if (ModelState.IsValid)
            {
                await _positionService.AddPositionAsync(position);
                return RedirectToAction(nameof(Index));
            }

            return View(position);            
        }

        // GET: Positions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            //var position = await _context.Positions.FindAsync(id);
            var position = await _positionService.GetPositionAsync((int)id);

            if (position == null) return NotFound();

            return View(position);
        }

        // POST: Positions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ticker,Date,PricePrediction")] Position position)
        {
            if (id != position.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    await _positionService.UpdatePositionAsync(position);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_positionService.PositionExists(position.Id)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(position);
        }

        // GET: Positions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var position = await _positionService.GetPositionAsync((int)id);

            if (position == null) return NotFound();

            return View(position);
        }

        // POST: Positions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var position = await _positionService.GetPositionAsync(id);

            await _positionService.DeleteAsync(position);

            return RedirectToAction(nameof(Index));
        }        
    }
}

WisdomTrade/WisdomTradeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WisdomTrade</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WisdomTrade</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Positions" asp-action="Index">Current Positions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="AlgorithmicTrading" asp-action="Index">Algorithmic Trading</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                ML Regression
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" href="https://github.com/Lorenzo-bulosan/StockPricePrediction/blob/master/StockPredictionLSTM.ipynb">LSTM</a>
                                <a class="nav-link text-dark" href="https://github.com/Lorenzo-bulosan/StockPricePrediction/blob/master/StockPredictionGRU.ipynb">GRU</a>
                            </div>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WisdomTradeApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WisdomTrade/WisdomTradeApp/Views/Shared/_TradingViewGraph.cshtml
@*graph element*@
<div class="tradingview-widget-container">
    <div id="Graph"></div>
</div>

@*function to draw graph of selected ticker*@
<script type="text/javascript">

    function DrawGraph(ticker) {
        new TradingView.widget(
            {
                "width": 980,
                "height": 400,
                //autosize": true,
                "symbol": ticker,
                "interval": "D",
                "timezone": "Etc/UTC",
                "theme": "light",
                "style": "1",
                "locale": "uk",
                "toolbar_bg": "#f1f3f6",
                "enable_publishing": false,
                "hide_side_toolbar": false,
                "allow_symbol_change": true,
                "container_id": "Graph"
            }
        );
    }

</script>

<script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>